# name: Deploy to main
# on:
#   push:
#     branches: [ main ]

# jobs:
#   redeploy_everything:
#     runs-on: ubuntu-latest
#     name: Deploying everything to the main cluster

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up SSH key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_SECRETE_KEY }}" > ~/.ssh/expensewise.pem
#           chmod 600 ~/.ssh/expensewise.pem

#       - name: Add EC2 to known_hosts
#         run: |
#           ssh-keyscan -H 52.66.246.32 >> ~/.ssh/known_hosts
#           chmod 644 ~/.ssh/known_hosts

#       - name: Deploy to EC2
#         run: |
#           ssh -i ~/.ssh/expensewise.pem ubuntu@52.66.246.32 << 'EOF'
#             cd expensewiseServer
#             git pull origin main
#             export PATH=/root/.nvm/versions/node/v22.13.1/bin:$PATH
#             npm install
#             nohup npm run start > server.log 2>&1 &
#           EOF

#   docker CI/CD
name: Deploy to main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          build-args:
            - MONGODB=${{ secrets.MONGODB }}
          push: true
          tags: yashh04/expenseserver:${{ github.sha }}
